[project]
name = "crosspoint-reader"
version = "0.1.0"
description = "Add your description here"
authors = [
    { name = "Unintendedsideeffects", email = "malcolmcosenza@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "clang-format>=21.1.8",
    "platformio>=6.1.18",
]
